server:
  port: 8999
  
eureka:
  instance:
    hostname: localhost

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: price-service
          uri: http://localhost:8081
          predicates:
            - Path=/price/**
          filters:
            - name: CircuitBreaker
              args: 
                name: price-service
                fallbackuri: forward:/priceServiceFallback
                
        - id: product-service
          uri: http://localhost:9555
          predicates:
            - Path=/v1/**
          filters:
            - name: CircuitBreaker
              args: 
                name: product-service
                fallbackuri: forward:/productServiceFallback
                
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMillieseconds: 5000
            
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream